#! /bin/sh

set -e

cd "$(dirname "$0")/.."

echo "=> Installing multifunction_button listener...\n"
sudo cp multifunction_button.py /usr/local/bin/
sudo chmod +x /usr/local/bin/multifunction_button.py

echo "=> Starting multifunction_button listener...\n"
sudo cp multifunction_button.sh /etc/init.d/
sudo chmod +x /etc/init.d/multifunction_button.sh

sudo update-rc.d multifunction_button.sh defaults
sudo /etc/init.d/multifunction_button.sh start

echo "multifunction_button listener installed.\n"
