#! /bin/sh

set -e

cd "$(dirname "$0")/.."

echo "=> Stopping multifunction_button listener...\n"
sudo update-rc.d multifunction_button.sh remove
sudo /etc/init.d/multifunction_button.sh stop

echo "=> Removing multifunction_button listener...\n"
sudo rm -rf /usr/local/bin/multifunction_button.py
sudo rm -rf /etc/init.d/multifunction_button.sh

echo "multifunction_button listener uninstalled.\n"
